services:
  - type: web
    name: pocket-ca
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --worker-class sync --workers 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GEMINI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
